### ISSUE TITLE
Choose a custom view size in pixels

### ISSUE THREAD

**Issue by jared-hughes** [jared-hughes/desmodder-gif-creator#2]
Still default to the screen width, but provide this as an option for high- or low-res to be selected without resizing the window.

It would be great to scale the canvas as well, to get instant feedback/preview.

**Comment by jared-hughes** [comment]
Suggested interface:

- show the selected width and height in separate text boxes
- update the width and height automatically when the viewport changes
- add a toggle (manual size) to allow the user to override this automatic updating. Automatically gets toggled ok when the user edits the field, and the user can toggle it back off to allow the size to automatically follow viewport size
- frame the graph paper with a box showing the visible region. Requires fit=contain so this can always be visible on the graphpaper
- show this frame whenever the popover is visible, and the size is manually chosen

**Comment by SlimRunner** [comment]
Another useful feature to consider on this is the graph scaling which is controlled by "targetPixelRatio". It could be another toggle that allows you to keep the scaling of your current viewport.

It is noteworthy that in order to achieve this, fractional sizes must be passed to asyncScreenshot() options and re-scale the output back up to the target size using the ratios. Letter-boxing must be taken into account though when doing this transformations. I'll put here in a moment a practical example using my [screenshot gist](https://gist.github.com/SlimRunner/d6b6ae58c22d1dfd2095861de8033a92) to illustrate my point.

**Comment by SlimRunner** [comment]
Running the following snippets with the above userscript results in the same scaling applied to both images.

Edit: forgot to add the sample graph I used, which doesn't change the result, but just to be organized [https://www.desmos.com/calculator/gq8cjyvgyz](https://www.desmos.com/calculator/gq8cjyvgyz)

```js
ds = new DescreenShot({
	width: 300,
	height: 300,
	mathBounds: {
		left: -7,
		right: 7,
		bottom: -7,
		top: 7
	},
	targetPixelRatio: 1
})
ds.saveImage();
```

```js
ds = new DescreenShot({
	width: 300 / 7 * 3,
	height: 300 / 7 * 3,
	mathBounds: {
		left: -3,
		right: 3,
		bottom: -3,
		top: 3
	},
	targetPixelRatio: 7 / 3,
	preserveAxisNumbers: true
})
ds.saveImage();
```

The output is two 300x300 images that preserve the thickness of the lines (relative to each other, but same logic applies to the viewport and any arbitrary size).
